const cricketersList = [
  {
    id: 1,
    name: "Virat Kohli",
    country: "India",
    date_of_birth: "1988-11-05",
    role: "Batsman",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm medium",
    career_stats: {
      matches: 274,
      runs: 12898,
      batting_average: 57.32,
      hundreds: 46,
      fifties: 65,
      wickets: 4,
      bowling_average: 166.25,
    },
    image_url: "images/virat.jpeg",
  },
  {
    id: 2,
    name: "Steve Smith",
    country: "Australia",
    date_of_birth: "1989-06-02",
    role: "Batsman",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm legbreak",
    career_stats: {
      matches: 139,
      runs: 7540,
      batting_average: 61.8,
      hundreds: 27,
      fifties: 31,
      wickets: 17,
      bowling_average: 56.47,
    },
    image_url: "images/steven-smith.png",
  },
  {
    id: 3,
    name: "Joe Root",
    country: "England",
    date_of_birth: "1990-12-30",
    role: "Batsman",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm offbreak",
    career_stats: {
      matches: 121,
      runs: 10429,
      batting_average: 50.87,
      hundreds: 29,
      fifties: 55,
      wickets: 30,
      bowling_average: 49.36,
    },
    image_url: "images/joe-root.jpg",
  },
  {
    id: 4,
    name: "Kane Williamson",
    country: "New Zealand",
    date_of_birth: "1990-08-08",
    role: "Batsman",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm offbreak",
    career_stats: {
      matches: 94,
      runs: 8124,
      batting_average: 54.89,
      hundreds: 28,
      fifties: 33,
      wickets: 29,
      bowling_average: 40.96,
    },
    image_url: "images/kane-williamson.jpg",
  },
  {
    id: 5,
    name: "Babar Azam",
    country: "Pakistan",
    date_of_birth: "1994-10-15",
    role: "Batsman",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm offbreak",
    career_stats: {
      matches: 47,
      runs: 3696,
      batting_average: 47.74,
      hundreds: 9,
      fifties: 26,
      wickets: 0,
      bowling_average: null,
    },
    image_url: "images/babar-azam.jpeg",
  },
  {
    id: 6,
    name: "Ben Stokes",
    country: "England",
    date_of_birth: "1991-06-04",
    role: "All-rounder",
    batting_style: "Left-hand bat",
    bowling_style: "Right-arm fast-medium",
    career_stats: {
      matches: 89,
      runs: 5320,
      batting_average: 36.0,
      hundreds: 11,
      fifties: 28,
      wickets: 195,
      bowling_average: 32.74,
    },
    image_url: "images/ben-stokes.png",
  },
  {
    id: 7,
    name: "Ravichandran Ashwin",
    country: "India",
    date_of_birth: "1986-09-17",
    role: "Bowler",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm offbreak",
    career_stats: {
      matches: 86,
      runs: 2931,
      batting_average: 27.0,
      hundreds: 5,
      fifties: 12,
      wickets: 442,
      bowling_average: 24.13,
    },
    image_url: "images/ravi-ashwin.png",
  },
  {
    id: 8,
    name: "Pat Cummins",
    country: "Australia",
    date_of_birth: "1993-05-08",
    role: "Bowler",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm fast",
    career_stats: {
      matches: 47,
      runs: 985,
      batting_average: 16.46,
      hundreds: 0,
      fifties: 2,
      wickets: 217,
      bowling_average: 21.5,
    },
    image_url: "images/pat-cummins.jpg",
  },
  {
    id: 9,
    name: "Quinton de Kock",
    country: "South Africa",
    date_of_birth: "1992-12-17",
    role: "Wicketkeeper",
    batting_style: "Left-hand bat",
    bowling_style: "Right-arm medium",
    career_stats: {
      matches: 54,
      runs: 3300,
      batting_average: 38.82,
      hundreds: 6,
      fifties: 22,
      wickets: 0,
      bowling_average: null,
    },
    image_url: "images/quinton-de-kock.jpg",
  },
  {
    id: 10,
    name: "MS Dhoni",
    country: "India",
    date_of_birth: "1981-07-07",
    role: "Wicketkeeper-Batsman",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm medium",
    career_stats: {
      matches: 90,
      runs: 4876,
      batting_average: 38.09,
      hundreds: 6,
      fifties: 33,
      wickets: 0,
      bowling_average: 0.0,
    },
    image_url: "images/msd.jpg",
  },
  {
    id: 11,
    name: "Rohit Sharma",
    country: "India",
    date_of_birth: "1987-04-30",
    role: "Batsman",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm offbreak",
    career_stats: {
      matches: 56,
      runs: 3677,
      batting_average: 46.54,
      hundreds: 10,
      fifties: 16,
      wickets: 2,
      bowling_average: 91.0,
    },
    image_url: "images/Rohit-sharma.jpeg",
  },
  {
    id: 12,
    name: "Hardik Pandya",
    country: "India",
    date_of_birth: "1993-10-11",
    role: "All-rounder",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm fast-medium",
    career_stats: {
      matches: 11,
      runs: 532,
      batting_average: 31.29,
      hundreds: 1,
      fifties: 4,
      wickets: 17,
      bowling_average: 31.05,
    },
    image_url: "images/hardik.jpeg",
  },
  {
    id: 13,
    name: "Shubman Gill",
    country: "India",
    date_of_birth: "1999-09-08",
    role: "Batsman",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm offbreak",
    career_stats: {
      matches: 22,
      runs: 1254,
      batting_average: 34.83,
      hundreds: 2,
      fifties: 6,
      wickets: 0,
      bowling_average: 0.0,
    },
    image_url: "images/shubman-gill.jpeg",
  },
  {
    id: 14,
    name: "Yuvraj Singh",
    country: "India",
    date_of_birth: "1981-12-12",
    role: "All-rounder",
    batting_style: "Left-hand bat",
    bowling_style: "Left-arm orthodox",
    career_stats: {
      matches: 40,
      runs: 1900,
      batting_average: 33.92,
      hundreds: 3,
      fifties: 11,
      wickets: 25,
      bowling_average: 35.2,
    },
    image_url: "images/yuvraj-singh.jpeg",
  },
  {
    id: 15,
    name: "Sourav Ganguly",
    country: "India",
    date_of_birth: "1972-07-08",
    role: "Batsman",
    batting_style: "Left-hand bat",
    bowling_style: "Right-arm medium",
    career_stats: {
      matches: 113,
      runs: 7212,
      batting_average: 42.17,
      hundreds: 16,
      fifties: 35,
      wickets: 32,
      bowling_average: 52.53,
    },
    image_url: "images/Sourav-ganguly.jpeg",
  },
  {
    id: 16,
    name: "Anil Kumble",
    country: "India",
    date_of_birth: "1970-10-17",
    role: "Bowler",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm legbreak",
    career_stats: {
      matches: 132,
      runs: 2506,
      batting_average: 17.77,
      hundreds: 1,
      fifties: 5,
      wickets: 619,
      bowling_average: 29.65,
    },
    image_url: "images/anil-kumble.jpeg",
  },
  {
    id: 17,
    name: "Zaheer Khan",
    country: "India",
    date_of_birth: "1978-10-07",
    role: "Bowler",
    batting_style: "Right-hand bat",
    bowling_style: "Left-arm fast-medium",
    career_stats: {
      matches: 92,
      runs: 1230,
      batting_average: 11.94,
      hundreds: 0,
      fifties: 1,
      wickets: 311,
      bowling_average: 32.94,
    },
    image_url: "images/zaheer-khan.jpg",
  },
  {
    id: 18,
    name: "Ravindra Jadeja",
    country: "India",
    date_of_birth: "1988-12-06",
    role: "All-rounder",
    batting_style: "Left-hand bat",
    bowling_style: "Left-arm orthodox",
    career_stats: {
      matches: 70,
      runs: 2878,
      batting_average: 36.56,
      hundreds: 3,
      fifties: 19,
      wickets: 275,
      bowling_average: 24.28,
    },
    image_url: "images/ravi-jadeja.jpeg",
  },
  {
    id: 19,
    name: "Rishab pant",
    country: "India",
    date_of_birth: "1986-09-17",
    role: "Batsman",
    batting_style: "Left-hand bat",
    bowling_style: "Right-arm offbreak",
    career_stats: {
      matches: 99,
      runs: 3309,
      batting_average: 27.46,
      hundreds: 5,
      fifties: 14,
      wickets: 516,
      bowling_average: 23.98,
    },
    image_url: "images/rishab-pant.jpeg",
  },
  {
    id: 20,
    name: "Rahul Dravid",
    country: "India",
    date_of_birth: "1973-01-11",
    role: "Batsman",
    batting_style: "Right-hand bat",
    bowling_style: "Right-arm offbreak",
    career_stats: {
      matches: 164,
      runs: 13288,
      batting_average: 52.31,
      hundreds: 36,
      fifties: 63,
      wickets: 1,
      bowling_average: 39.0,
    },
    image_url: "images/dravid.jpg",
  },
]; 

// image name country role
function displayCricketersData() {
  cricketersList.forEach((v) => {
    const cricDiv = document.createElement("div");
    cricDiv.classList.add('cricketerCard')
    const cricImg = document.createElement("img");
    cricImg.src = v.image_url;
    cricImg.alt = v.name;
    cricImg.height = 200;
    const cricName = document.createElement("h2");
    cricName.textContent = v.name;
    const cricCountry = document.createElement("h3");
    cricCountry.textContent = v.country;
    const cricRole = document.createElement("p");
    cricRole.textContent = v.role;

    cricDiv.append(cricImg, cricName, cricCountry, cricRole);
    document.getElementById("cricketers").append(cricDiv);
  });
};
displayCricketersData();
